name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this solve? Why do you need this feature?
      placeholder: I want to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: It would be great if...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternative approaches you've tried?

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application does this affect?
      options:
        - GUI
        - Remap Daemon
        - CLI Tools
        - OpenRazer Integration
        - Macro Engine
        - Profile Management
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, screenshots, or additional information
